# Site settings
title: Flip On It
email: mobileapps@codecomputerlove.com
description: > # this means to ignore newlines until "baseurl:"
  Meta description for search
baseurl: "" # the subpath of your site, e.g. /blog/


# Build settings
markdown: kramdown
exclude: ["vendor"]
