# Site settings
title: Flip On It - Apple Watch App
email: mobileapps@codecomputerlove.com
description: > # this means to ignore newlines until "baseurl:"
  Flip on it is an app for the Apple watch designed to help you make decisions. Download from the App Store today.
baseurl: "" # the subpath of your site, e.g. /blog/


# Build settings
markdown: kramdown
exclude: ["vendor"]
